// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: emails.sql

package database

import (
	"context"
)

const getManagerMailIDs = `-- name: GetManagerMailIDs :many
SELECT email FROM users u JOIN user_roles ur ON u.id = ur.user_id WHERE role_name=$1
`

func (q *Queries) GetManagerMailIDs(ctx context.Context, roleName string) ([]string, error) {
	rows, err := q.db.Query(ctx, getManagerMailIDs, roleName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var email string
		if err := rows.Scan(&email); err != nil {
			return nil, err
		}
		items = append(items, email)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
