// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: locks.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createLock = `-- name: CreateLock :one
INSERT INTO locks (timeout, name, created_by, description) VALUES ($1, $2, $3, $4)
RETURNING id, timeout, name, created_by, created_at, description, access
`

type CreateLockParams struct {
	Timeout     time.Time `json:"timeout"`
	Name        string    `json:"name"`
	CreatedBy   uuid.UUID `json:"created_by"`
	Description string    `json:"description"`
}

func (q *Queries) CreateLock(ctx context.Context, arg CreateLockParams) (Lock, error) {
	row := q.db.QueryRowContext(ctx, createLock,
		arg.Timeout,
		arg.Name,
		arg.CreatedBy,
		arg.Description,
	)
	var i Lock
	err := row.Scan(
		&i.ID,
		&i.Timeout,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Description,
		&i.Access,
	)
	return i, err
}

const getLockById = `-- name: GetLockById :one
SELECT id, timeout, name, created_by, created_at, description, access FROM locks WHERE id=$1
`

func (q *Queries) GetLockById(ctx context.Context, id uuid.UUID) (Lock, error) {
	row := q.db.QueryRowContext(ctx, getLockById, id)
	var i Lock
	err := row.Scan(
		&i.ID,
		&i.Timeout,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Description,
		&i.Access,
	)
	return i, err
}

const getLocksByFilter = `-- name: GetLocksByFilter :many
SELECT id, timeout, name, created_by, created_at, description, access FROM locks
WHERE
    name ILIKE $1
    AND (
        $2::uuid IS NULL OR
        $2::uuid = created_by
    )
`

type GetLocksByFilterParams struct {
	Name      string        `json:"name"`
	CreatedBy uuid.NullUUID `json:"created_by"`
}

func (q *Queries) GetLocksByFilter(ctx context.Context, arg GetLocksByFilterParams) ([]Lock, error) {
	rows, err := q.db.QueryContext(ctx, getLocksByFilter, arg.Name, arg.CreatedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lock
	for rows.Next() {
		var i Lock
		if err := rows.Scan(
			&i.ID,
			&i.Timeout,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Description,
			&i.Access,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLockDetails = `-- name: UpdateLockDetails :one
UPDATE locks
SET
    name = $2,
    timeout = $3,
    description = $4
WHERE
    id = $1
RETURNING id, timeout, name, created_by, created_at, description, access
`

type UpdateLockDetailsParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Timeout     time.Time `json:"timeout"`
	Description string    `json:"description"`
}

func (q *Queries) UpdateLockDetails(ctx context.Context, arg UpdateLockDetailsParams) (Lock, error) {
	row := q.db.QueryRowContext(ctx, updateLockDetails,
		arg.ID,
		arg.Name,
		arg.Timeout,
		arg.Description,
	)
	var i Lock
	err := row.Scan(
		&i.ID,
		&i.Timeout,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Description,
		&i.Access,
	)
	return i, err
}
